### ISSUE TITLE
Add Import Validation for Emissions Data Codes

### ISSUE THREAD

**Issue by AmandaMNelson** [US-EPA-CAMD/easey-ecmps-ui#1020]
When a user imports an emissions file where a code (spanScaleCode, testResultCode, gasLevelCode, etc.) is not valid,
an import check validation message should appear, directing them to enter a valid code.

Should the response message include a list of valid codes?

Should this be covered under an existing Import check? (17?)

**Comment by JanellC** [comment]
Need confirmation if this bug is valid @acollad1

**Comment by jwhitehead77** [comment]
duplicate of #5096
