### ISSUE TITLE
Change Naming in QA MATS Import Modal

### ISSUE THREAD

**Issue by AmandaMNelson** [US-EPA-CAMD/easey-ecmps-ui#1293]
Change modal and test type dropdown names in QA MATS Import modal

Steps to Recreate:
Navigate to QA & Certifications --> Test Data
Open and Checkout a configuration
Click Import Data button
Select MATS PDF/XML from the dropdown

The title of the modal should be "Import MATS PDF/XML Data"
The title of the second dropdown should be "Test Type" without the word Group

**Comment by jwhitehead77** [comment]
this has already been done and ready to verify

**Comment by mosesdeeCVP** [comment]
[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBeEF1QVE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--67bb0f8f361fbe98b06f7dfa84929c6ad4334cc5/Import%20MATS%20PDF-XML%20Data.png)

**Comment by mosesdeeCVP** [comment]
Updates have been made
