### ISSUE TITLE
Displaying data issues in the workspace

### ISSUE THREAD

**Issue by ntknguyen** [US-EPA-CAMD/easey-ecmps-ui#1407]
The calculated value and report errors are not displaying in the workspace view template.  However they are displaying in the global view.
Example:
1. Import 2023 Q3 emissions from historical for oris 8906, CP30, 31RH, 31SH
2. Select Hourly NOx Rate CEMS view for 31RH and apply filter
3. There is no data displaying in the Report Errors and Calculated columns

**Comment by mark-hayward-erg** [comment]
Duplicate of https://github.com/US-EPA-CAMD/easey-ui/issues/6181
