### ISSUE TITLE
MP Location Attributes and Relationships Data Test Automation v1.0

### ISSUE THREAD

**Issue by mosesdeeCVP** [US-EPA-CAMD/easey-ecmps-ui#923]
MP Location Attributes and Relationships Data Test Automation v1.0

## Context
Create one script that complete the following actions for MP Location Attributes  Create, Edit, Evaluate, Revert to Offical Record.
The same script will have View for Relationships Data

**Comment by JanellC** [comment]
duplicate. ticket no longer needed
