### ISSUE TITLE
Retest only: Bug: QA & Certification - Test Summary Data Export not working

### ISSUE THREAD

**Issue by vishnunavuluri** [US-EPA-CAMD/easey-ecmps-ui#981]
**Issue:** 
When a user wishes to export Test Summary data under QA Certification Data and they make the needed selections, the system doesn't display any data for Test Summary inspite of it being available in the DB

Steps to Recreate:
1. Log in to ECMPS
2. Navigate to the Export functionality and open Harrison Power Station (2)
3. Check the QA & Certification option and preview data
You will see that there is no data displayed for Test Summary even though it is available in the DB

**Comment by mosesdeeCVP** [comment]
Test Sum and QA Cert in 1 Export logged in
![Test Sum and QA Cert in 1 Export logged in.png](https://images.zenhubusercontent.com/5f807025564a417cbcdf6d69/a3de3529-e9d7-4a55-81fa-a73bd89f4d84)

Test Sum and QA Cert in 1 Export logged out
![Test Sum and QA Cert in 1 Export logged out.png](https://images.zenhubusercontent.com/5f807025564a417cbcdf6d69/771aa148-d664-4e44-b814-c04d2c8aae34)

**Comment by mosesdeeCVP** [comment]
Functionality works as expected
